apiVersion: apps/v1
kind: Deployment
metadata:
 name: nzngarage-frontend
spec:
 replicas: 1
 selector:
     matchLabels:
       app: nzngarage-frontend
 template:
   metadata:
     labels:
       app: nzngarage-frontend
   spec:     # pod spec                  
     containers:
     - name: nzngarage-frontend
       image: us.icr.io/nzngarage/nzngarage-frontend:latest
       ports:
         - containerPort: 8080
       imagePullPolicy: Always