apiVersion: v1
kind: Service
metadata:
  labels:
    app: nzngarage-frontend
  name: nzngarage-frontend-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nzngarage-frontend
  type: NodePort