apiVersion: v1
kind: Service
metadata:
  labels:
    app: nzngarage-frontend
  name: nzngarage-frontend-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: nzngarage-frontend 